# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'recipes/*'
    - 'examples/*'
    - 'bin/*'

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 26

Metrics/ModuleLength:
  Max: 125

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Exclude:
    - 'libraries/matchers.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/WordArray:
  Enabled: false
