language: ruby
rvm:
  - 2.1
  - 2.2.6
  - 2.3.1

before_install:
  - gem update bundler
  - git clone https://github.com/HewlettPackard/oneview-sdk-ruby
  - cd oneview-sdk-ruby
  - gem build oneview-sdk.gemspec
  - gem install ./oneview-sdk-3.1.0.gem
  - cd ..
  - rm -rf oneview-sdk-ruby

script:
  - rake test
