# This is a basic workflow to help you get started with Actions

name: Automated create PR

# Controls when the action will run. Triggers the workflow on push event
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Create PR if the commit message contains #pr hashtag
    steps:
    - name: Create PR
      uses: funivan/github-autopr@0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: .head_commit.message .*#pr.*
